services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  app:
    env_file: .env
    build: .
    ports:
      - "3010:3010"  
    volumes:
      - .:/src             
      - ./node_modules:/src/node_modules
    depends_on:
      - postgres
      - mailhog
    environment:
      API_PORT: ${API_PORT}
      PG_TYPE: ${PG_TYPE}
      PG_PORT: ${PG_PORT}
      HOST: ${HOST}
      USERNAME: ${DB_USER}
      DATABASE: ${DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      CACHE_TTL_L1: ${CACHE_TTL_L1}
      CACHE_TTL_L2: ${CACHE_TTL_L2}

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - library-app-pg-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    environment:
      MH_STORAGE: maildir                  # switch from in-memory to maildir on disk :contentReference[oaicite:0]{index=0}
      MH_MAILDIR_PATH: /mailhog/data       # where on the container to store the maildir
    volumes:
      - ./mailhog_data:/mailhog/data
    ports:
      - '1025:1025'  # SMTP
      - '8025:8025'  # Web UI

volumes:
  redis-data:
  library-app-pg-data: