---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library-api
  template:
    metadata:
      labels:
        app: library-api
    spec:
      containers:
      - name: library-api
        image: __IMAGE__
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3010
        envFrom:
        - configMapRef:
            name: library-api-config
        - secretRef:
            name: library-api-secret

        startupProbe:
          httpGet:
            path: /health/ping
            port: 3010
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 15  # 5s × 15 = 75s max boot time before restart

        readinessProbe:
          httpGet:
            path: /health/queue
            port: 3010
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health/ping
            port: 3010
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 2
          failureThreshold: 3  # 3 × 15s = 45s before restart
---
apiVersion: v1
kind: Service
metadata:
  name: library-api
spec:
  type: LoadBalancer
  selector:
    app: library-api
  ports:
  - port: 80
    targetPort: 3010
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ExternalName
  externalName: master.library-app-cache.vcqzl5.sae1.cache.amazonaws.com
  ports:
  - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  type: ExternalName
  externalName: library-app-db.cfimysa8eve5.sa-east-1.rds.amazonaws.com
  ports:
  - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  type: ExternalName
  externalName: sandbox.smtp.mailtrap.io
  ports:
  - port: 2525
