---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library-api
  template:
    metadata:
      labels:
        app: library-api
    spec:
      containers:
      - name: library-api
        image: __IMAGE__
        ports:
        - containerPort: 3010
        envFrom:
        - configMapRef:
            name: library-api-config
        - secretRef:
            name: library-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: library-api
spec:
  type: LoadBalancer
  selector:
    app: library-api
  ports:
  - port: 80
    targetPort: 3010
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ExternalName
  externalName: master.library-app-cache.vcqzl5.sae1.cache.amazonaws.com
  ports:
  - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  type: ExternalName
  externalName: library-app-db.cfimysa8eve5.sa-east-1.rds.amazonaws.com
  ports:
  - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  type: ExternalName
  externalName: sandbox.smtp.mailtrap.io
  ports:
  - port: 2525
