---
name: library-api-ci

concurrency:
  group: deploy-api
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  build-and-generate-k8s:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: >-
            ${{ secrets.DOCKER_HUB_USERNAME }}/library-api:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Split .env for ConfigMap
        run: |
          grep -vE '^(DB_USER|DB_PASSWORD|BB_PASS|JWT_SECRET|MAIL_PASSWORD)' .env > config.env

      - name: Split .env for Secret
        run: |
          grep -E '^(DB_USER|DB_PASSWORD|BB_PASS|JWT_SECRET|MAIL_PASSWORD)' .env > secret.env

      - name: Generate ConfigMap YAML
        run: |
          kubectl create configmap library-api-config \
            --from-env-file=config.env \
            --dry-run=client \
            -o yaml > src/infrastructure/cloud/k8s/configmap.yaml

      - name: Generate Secret YAML
        run: |
          kubectl create secret generic library-api-secret \
            --from-env-file=secret.env \
            --type=Opaque \
            --dry-run=client \
            -o yaml > src/infrastructure/cloud/k8s/secret.yaml

      - name: Render Deployment manifest
        run: |
          sed "s|__IMAGE__|${{ secrets.DOCKER_HUB_USERNAME }}/library-api:${{ github.sha }}|" \
            src/infrastructure/cloud/k8s/deployment.tpl.yaml \
            > src/infrastructure/cloud/k8s/deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f src/infrastructure/cloud/k8s/configmap.yaml \
                         -f src/infrastructure/cloud/k8s/secret.yaml \
                         -f src/infrastructure/cloud/k8s/deployment.yaml
